// Ready-made policy packs. "Recommended" is general agent safety; the rest map
// to real compliance controls. Each template matches the engine's shape
// (actor/action/resource globs + optional conditions). Adding a pack upserts its
// policies into the org (idempotent on policy_id), so admins can turn a whole
// framework on in one click and then tune individual rules.

export type TemplateCondition = { field: string; op: string; value: unknown };
export type PolicyTemplate = {
  policy_id: string;
  effect: "allow" | "deny" | "require_approval";
  priority: number;
  actor?: string;
  action: string;
  resource?: string;
  conditions?: TemplateCondition[];
  approvals_required?: number;
  description: string;
  control?: string; // e.g. "SOC 2 CC6.1"
};

export type PolicyPack = {
  key: string;
  name: string;
  framework: string;
  blurb: string;
  recommended?: boolean;
  templates: PolicyTemplate[];
};

export const POLICY_PACKS: PolicyPack[] = [
  {
    key: "ai-usage",
    name: "AI request policy",
    framework: "AI usage controls",
    recommended: true,
    blurb: "The rules StileAI enforces on what employees send to AI tools. Each rule decides what happens when a request contains that kind of content — allow, ask an admin, or block. This is what drives approve / deny / admin-approval.",
    templates: [
      { policy_id: "ai-secrets", effect: "deny", priority: 10, action: "secrets", description: "Block AI requests that contain passwords, API keys, or secrets.", control: "Secret protection" },
      { policy_id: "ai-phi", effect: "deny", priority: 10, action: "phi", description: "Block AI requests that contain health information (PHI).", control: "HIPAA" },
      { policy_id: "ai-pii", effect: "require_approval", priority: 20, action: "pii", approvals_required: 1, description: "Send AI requests containing personal data (PII) to an admin for approval.", control: "Privacy / PII" },
      { policy_id: "ai-client-data", effect: "require_approval", priority: 20, action: "client_data", approvals_required: 1, description: "Send AI requests containing customer or client data to an admin for approval.", control: "Client confidentiality" },
      { policy_id: "ai-financial", effect: "require_approval", priority: 20, action: "financial", approvals_required: 1, description: "Send AI requests containing financial information to an admin for approval.", control: "Financial data" },
      { policy_id: "ai-legal", effect: "require_approval", priority: 20, action: "legal", approvals_required: 1, description: "Send AI requests containing legal or contract documents to an admin for approval.", control: "Legal / contracts" },
      { policy_id: "ai-source-code", effect: "require_approval", priority: 20, action: "source_code", approvals_required: 1, description: "Send AI requests containing source code to an admin for approval.", control: "Source-code protection" },
    ],
  },
  {
    key: "baseline",
    name: "Recommended baseline",
    framework: "General agent safety",
    recommended: true,
    blurb: "The starting set every deployment should have: block the irreversible, auto-allow the harmless, and put a human on money and mass changes.",
    templates: [
      { policy_id: "baseline-deny-db-drop", effect: "deny", priority: 10, action: "db.drop*", description: "Dropping tables or databases is never allowed via an agent.", control: "Destructive-action guard" },
      { policy_id: "baseline-deny-table-delete", effect: "deny", priority: 15, action: "db.delete", resource: "table:*", description: "Deleting an entire table is blocked; delete specific records instead.", control: "Destructive-action guard" },
      { policy_id: "baseline-allow-reads", effect: "allow", priority: 30, action: "*.read", description: "Read-only actions are allowed for any actor.", control: "Least-friction reads" },
      { policy_id: "baseline-allow-search", effect: "allow", priority: 31, action: "*.search", description: "Search and list actions are allowed.", control: "Least-friction reads" },
      { policy_id: "baseline-approve-large-payment", effect: "require_approval", priority: 40, action: "payment.charge", approvals_required: 1, conditions: [{ field: "amount", op: "gt", value: 100 }], description: "Charges over $100 need one human approval.", control: "Money-movement control" },
      { policy_id: "baseline-approve-record-delete", effect: "require_approval", priority: 45, action: "db.delete", approvals_required: 1, description: "Deleting a specific record needs human approval.", control: "Destructive-action control" },
      { policy_id: "baseline-approve-external-email", effect: "require_approval", priority: 50, action: "email.send", approvals_required: 1, description: "Sending outbound email needs approval.", control: "Data-egress control" },
    ],
  },
  {
    key: "soc2",
    name: "SOC 2",
    framework: "Trust Services Criteria",
    blurb: "Change management, access, and audit-integrity controls agents commonly touch.",
    templates: [
      { policy_id: "soc2-approve-prod-config", effect: "require_approval", priority: 22, action: "config.*", resource: "env:prod*", approvals_required: 1, description: "Production configuration changes require human approval.", control: "SOC 2 CC8.1 (Change mgmt)" },
      { policy_id: "soc2-deny-disable-audit", effect: "deny", priority: 8, action: "*.disable_audit", description: "Disabling the audit trail is never allowed.", control: "SOC 2 CC7.2 (Monitoring)" },
      { policy_id: "soc2-approve-access-grant", effect: "require_approval", priority: 24, action: "iam.grant*", approvals_required: 1, description: "Granting access or roles requires approval.", control: "SOC 2 CC6.1 (Logical access)" },
      { policy_id: "soc2-approve-data-export", effect: "require_approval", priority: 26, action: "*.export", approvals_required: 1, description: "Exporting data requires approval.", control: "SOC 2 CC6.7 (Data transfer)" },
    ],
  },
  {
    key: "hipaa",
    name: "HIPAA",
    framework: "Protected Health Information",
    blurb: "Guardrails for anything touching PHI — access, export, and disclosure.",
    templates: [
      { policy_id: "hipaa-approve-phi-read", effect: "require_approval", priority: 28, action: "*.read", resource: "phi:*", approvals_required: 1, description: "Reading protected health information requires approval.", control: "HIPAA §164.312(a) (Access control)" },
      { policy_id: "hipaa-approve-phi-export", effect: "require_approval", priority: 20, action: "*.export", resource: "phi:*", approvals_required: 1, description: "Exporting PHI requires approval.", control: "HIPAA §164.312(e) (Transmission security)" },
      { policy_id: "hipaa-deny-phi-delete", effect: "deny", priority: 12, action: "*.delete", resource: "phi:*", description: "Deleting PHI records via an agent is blocked (retention).", control: "HIPAA §164.316(b) (Retention)" },
      { policy_id: "hipaa-approve-phi-disclose", effect: "require_approval", priority: 21, action: "*.share", resource: "phi:*", approvals_required: 1, description: "Disclosing PHI to any party requires approval.", control: "HIPAA §164.508 (Disclosure)" },
    ],
  },
  {
    key: "pci",
    name: "PCI-DSS",
    framework: "Cardholder data",
    blurb: "Keep agents away from storing PANs and put approvals on card operations.",
    templates: [
      { policy_id: "pci-deny-store-pan", effect: "deny", priority: 9, action: "card.store", description: "Storing full card numbers (PAN) is never allowed.", control: "PCI-DSS 3.2 (No PAN storage)" },
      { policy_id: "pci-deny-log-pan", effect: "deny", priority: 9, action: "log.write", resource: "card:*", description: "Writing card data to logs is blocked.", control: "PCI-DSS 3.4 (Render PAN unreadable)" },
      { policy_id: "pci-approve-charge", effect: "require_approval", priority: 42, action: "payment.charge", approvals_required: 1, description: "Card charges require approval.", control: "PCI-DSS 10 (Track access)" },
      { policy_id: "pci-approve-refund", effect: "require_approval", priority: 42, action: "payment.refund", approvals_required: 1, description: "Refunds require approval.", control: "PCI-DSS 10 (Track access)" },
    ],
  },
  {
    key: "gdpr",
    name: "GDPR",
    framework: "Personal data",
    blurb: "Approvals around personal-data export, erasure, and third-party sharing.",
    templates: [
      { policy_id: "gdpr-approve-pii-export", effect: "require_approval", priority: 27, action: "*.export", resource: "pii:*", approvals_required: 1, description: "Exporting personal data requires approval.", control: "GDPR Art. 5 (Integrity)" },
      { policy_id: "gdpr-approve-erasure", effect: "require_approval", priority: 27, action: "user.delete", approvals_required: 1, description: "Erasing a user's data requires approval (right to be forgotten).", control: "GDPR Art. 17 (Erasure)" },
      { policy_id: "gdpr-approve-3p-share", effect: "require_approval", priority: 25, action: "data.share", resource: "external:*", approvals_required: 1, description: "Sharing personal data with third parties requires approval.", control: "GDPR Art. 44 (Transfers)" },
    ],
  },
  {
    key: "iso27001",
    name: "ISO 27001",
    framework: "Information security",
    blurb: "Privileged access and cryptographic-material controls.",
    templates: [
      { policy_id: "iso-approve-privileged", effect: "require_approval", priority: 23, action: "iam.*", approvals_required: 1, description: "Privileged identity/access changes require approval.", control: "ISO 27001 A.9 (Access control)" },
      { policy_id: "iso-approve-crypto", effect: "require_approval", priority: 18, action: "key.*", approvals_required: 1, description: "Key and certificate operations require approval.", control: "ISO 27001 A.10 (Cryptography)" },
      { policy_id: "iso-deny-disable-security", effect: "deny", priority: 8, action: "security.disable", description: "Disabling security controls is never allowed.", control: "ISO 27001 A.12 (Operations security)" },
    ],
  },
  {
    key: "nist-ai",
    name: "NIST AI RMF",
    framework: "AI risk management",
    blurb: "AI-specific limits: model deployment, autonomy escalation, and new tool/connections.",
    templates: [
      { policy_id: "nist-approve-model-deploy", effect: "require_approval", priority: 24, action: "model.deploy", approvals_required: 1, description: "Deploying or updating a model requires approval.", control: "NIST AI RMF GOVERN 1.1" },
      { policy_id: "nist-approve-escalation", effect: "require_approval", priority: 20, action: "agent.escalate*", approvals_required: 1, description: "An agent expanding its own privileges requires approval.", control: "NIST AI RMF MANAGE 2.1" },
      { policy_id: "nist-approve-tool-connect", effect: "require_approval", priority: 26, action: "tool.install", approvals_required: 1, description: "Connecting a new tool or MCP server requires approval.", control: "NIST AI RMF MAP 4.1" },
    ],
  },
  {
    key: "governance",
    name: "Agent guardrail governance",
    framework: "Guardrail integrity",
    recommended: true,
    blurb: "Protects the guardrail itself — no agent can edit its own rules — and backstops everything else with a default-deny catch-all.",
    templates: [
      { policy_id: "governance-deny-policy-edit-policy", effect: "deny", priority: 3, actor: "agent:*", action: "policy.*", description: "An agent can never create, edit, or disable the policies that constrain it.", control: "Guardrail self-protection" },
      { policy_id: "governance-deny-policy-edit-interlock", effect: "deny", priority: 3, actor: "agent:*", action: "interlock.*", description: "An agent can never modify the Interlock guardrail configuration itself.", control: "Guardrail self-protection" },
      { policy_id: "governance-catch-all-deny", effect: "deny", priority: 999, action: "*", resource: "*", description: "Default-deny backstop: anything not explicitly allowed or approved by a higher-precedence rule is blocked. Enabling this pack flips the org's posture to deny-by-default — make sure the allows/approvals you need are already in place.", control: "Default-deny posture" },
    ],
  },
  {
    key: "access-security",
    name: "Access & identity",
    framework: "Access control",
    blurb: "Keeps agents away from permissions, credentials, security settings, impersonation, and the audit trail.",
    templates: [
      { policy_id: "access-security-deny-permission-grant", effect: "deny", priority: 10, action: "permissions.grant", description: "Granting permissions is an access-control change and is off-limits to agents.", control: "Access-control guard" },
      { policy_id: "access-security-deny-role-assign", effect: "deny", priority: 10, action: "role.assign", description: "Assigning roles is an access-control change and is off-limits to agents.", control: "Access-control guard" },
      { policy_id: "access-security-deny-sharing-modify", effect: "deny", priority: 10, action: "sharing.modify", description: "Changing sharing/visibility settings is an access-control change and is off-limits to agents.", control: "Access-control guard" },
      { policy_id: "access-security-deny-credential-ops", effect: "deny", priority: 10, action: "credential.*", description: "Creating, reading, or rotating credentials via an agent is never allowed.", control: "Secrets guard" },
      { policy_id: "access-security-deny-apikey-create", effect: "deny", priority: 10, action: "apikey.create", description: "Minting new API keys via an agent is never allowed.", control: "Secrets guard" },
      { policy_id: "access-security-deny-secret-rotate", effect: "deny", priority: 10, action: "secret.rotate", description: "Rotating secrets via an agent is never allowed.", control: "Secrets guard" },
      { policy_id: "access-security-deny-security-settings", effect: "deny", priority: 10, action: "security.*", description: "Changing security settings via an agent is never allowed.", control: "Security-settings guard" },
      { policy_id: "access-security-deny-mfa-disable", effect: "deny", priority: 10, action: "mfa.disable", description: "Disabling multi-factor authentication via an agent is never allowed.", control: "Security-settings guard" },
      { policy_id: "access-security-deny-sso-configure", effect: "deny", priority: 10, action: "sso.configure", description: "Reconfiguring SSO via an agent is never allowed.", control: "Security-settings guard" },
      { policy_id: "access-security-deny-impersonation", effect: "deny", priority: 10, action: "user.impersonate", description: "An agent impersonating another user is never allowed.", control: "Identity guard" },
      { policy_id: "access-security-deny-disable-audit", effect: "deny", priority: 8, action: "audit.disable", description: "Disabling the audit trail is never allowed.", control: "Audit-integrity guard" },
      { policy_id: "access-security-deny-disable-logging", effect: "deny", priority: 8, action: "logging.disable", description: "Disabling logging is never allowed.", control: "Audit-integrity guard" },
      { policy_id: "access-security-approve-account-create", effect: "require_approval", priority: 24, action: "account.create", approvals_required: 1, description: "Creating a new account requires human approval.", control: "Provisioning control" },
      { policy_id: "access-security-approve-user-create", effect: "require_approval", priority: 24, action: "user.create", approvals_required: 1, description: "Creating a new user requires human approval.", control: "Provisioning control" },
    ],
  },
  {
    key: "data-integrity",
    name: "Database & data integrity",
    framework: "Data safety",
    blurb: "Blocks table-level wipes outright and puts approval on schema changes and restores/rollbacks.",
    templates: [
      { policy_id: "data-integrity-deny-truncate", effect: "deny", priority: 12, action: "db.truncate", description: "Truncating a table via an agent is never allowed.", control: "Destructive-action guard" },
      { policy_id: "data-integrity-approve-schema-migrate", effect: "require_approval", priority: 22, action: "db.migrate", approvals_required: 1, description: "Running a schema migration requires human approval.", control: "Change-management control" },
      { policy_id: "data-integrity-approve-schema-alter", effect: "require_approval", priority: 22, action: "db.alter", approvals_required: 1, description: "Altering a schema requires human approval.", control: "Change-management control" },
      { policy_id: "data-integrity-approve-restore", effect: "require_approval", priority: 22, action: "db.restore", approvals_required: 1, description: "Restoring a database from backup requires human approval.", control: "Data-recovery control" },
      { policy_id: "data-integrity-approve-rollback", effect: "require_approval", priority: 22, action: "db.rollback", approvals_required: 1, description: "Rolling back a database change requires human approval.", control: "Data-recovery control" },
    ],
  },
  {
    key: "payments-plus",
    name: "Payments & financial (extended)",
    framework: "Financial controls",
    blurb: "A hard ceiling on charges, approvals on refunds and payouts, and a lock on bank details and crypto conversion.",
    templates: [
      { policy_id: "payments-plus-deny-payment-ceiling", effect: "deny", priority: 14, action: "payment.charge", conditions: [{ field: "amount", op: "gt", value: 10000 }], description: "Hard ceiling: charges over $10,000 are never auto-run by an agent, regardless of any approval tier below.", control: "Money-movement ceiling" },
      { policy_id: "payments-plus-approve-refund", effect: "require_approval", priority: 26, action: "refund.issue", approvals_required: 1, conditions: [{ field: "amount", op: "gt", value: 100 }], description: "Refunds over $100 require human approval.", control: "Money-movement control" },
      { policy_id: "payments-plus-approve-payout", effect: "require_approval", priority: 26, action: "payout.send", approvals_required: 1, description: "Sending a payout requires human approval.", control: "Money-movement control" },
      { policy_id: "payments-plus-approve-transfer", effect: "require_approval", priority: 26, action: "transfer.create", approvals_required: 1, description: "Creating a transfer requires human approval.", control: "Money-movement control" },
      { policy_id: "payments-plus-deny-bank-details-change", effect: "deny", priority: 10, action: "payment.update_bank_details", description: "Changing payout bank details via an agent is never allowed.", control: "Payout-fraud guard" },
      { policy_id: "payments-plus-deny-crypto", effect: "deny", priority: 12, action: "crypto.*", description: "Cryptocurrency operations via an agent are never allowed.", control: "Money-movement guard" },
      { policy_id: "payments-plus-deny-payment-convert", effect: "deny", priority: 12, action: "payment.convert", description: "Converting funds between currencies/instruments via an agent is never allowed.", control: "Money-movement guard" },
    ],
  },
  {
    key: "infra",
    name: "Infrastructure & deploys",
    framework: "Operational safety",
    blurb: "Approval on capacity-affecting and deploy operations, and a hard deny on DNS changes.",
    templates: [
      { policy_id: "infra-approve-server-terminate", effect: "require_approval", priority: 24, action: "server.terminate", approvals_required: 1, description: "Terminating a server requires human approval.", control: "Operational-safety control" },
      { policy_id: "infra-approve-scale-down", effect: "require_approval", priority: 24, action: "instance.scale_down", approvals_required: 1, description: "Scaling down instances requires human approval.", control: "Operational-safety control" },
      { policy_id: "infra-approve-cluster-ops", effect: "require_approval", priority: 24, action: "cluster.*", approvals_required: 1, description: "Cluster operations require human approval.", control: "Operational-safety control" },
      { policy_id: "infra-deny-dns", effect: "deny", priority: 12, action: "dns.*", description: "DNS changes via an agent are never allowed — a bad record can cause a full outage.", control: "Outage-prevention guard" },
      { policy_id: "infra-approve-deploy", effect: "require_approval", priority: 24, action: "deploy.*", approvals_required: 1, description: "Deploying requires human approval. This approves ALL deploys for now; scoping to production only (env eq prod) needs an enrichment field the tool call doesn't currently carry.", control: "Change-management control" },
    ],
  },
  {
    key: "trust-tiers",
    name: "Actor trust tiers",
    framework: "Actor-based control",
    blurb: "Reduces approval fatigue for a proven internal agent on reads, sandboxes newly deployed agents, and backstops writes from unrecognized actors.",
    templates: [
      { policy_id: "trust-tiers-allow-trusted-agent-reads", effect: "allow", priority: 34, actor: "agent:internal-ops", action: "*.read", description: "Reduces approval fatigue for the proven internal-ops agent on read-only actions. Reads only, and this priority is below every deny above, so it never overrides a hard deny.", control: "Trusted-actor allowlist" },
      { policy_id: "trust-tiers-approve-probation-agent", effect: "require_approval", priority: 28, actor: "agent:probation-*", action: "*", approvals_required: 1, description: "Newly deployed agents (actor names prefixed agent:probation-) require approval on every action during a probation period.", control: "New-actor probation" },
      { policy_id: "trust-tiers-deny-unknown-delete", effect: "deny", priority: 35, actor: "*", action: "*.delete", description: "Default-deny-on-writes backstop for delete actions: sits just above the catch-all so any actor without an explicit allow/approval at a lower priority number is blocked. Narrow the actor glob to exempt specific known agents.", control: "Unknown-actor write backstop" },
      { policy_id: "trust-tiers-deny-unknown-write", effect: "deny", priority: 35, actor: "*", action: "*.write", description: "Default-deny-on-writes backstop for write actions: sits just above the catch-all so any actor without an explicit allow/approval at a lower priority number is blocked. Narrow the actor glob to exempt specific known agents.", control: "Unknown-actor write backstop" },
      { policy_id: "trust-tiers-deny-unknown-create", effect: "deny", priority: 35, actor: "*", action: "*.create", description: "Default-deny-on-writes backstop for create actions: sits just above the catch-all so any actor without an explicit allow/approval at a lower priority number is blocked. Narrow the actor glob to exempt specific known agents.", control: "Unknown-actor write backstop" },
    ],
  },
  {
    key: "velocity",
    name: "Velocity & context",
    framework: "Runaway-agent & context controls",
    blurb: "Catches the things a single-action policy can't see: mass or external email blasts, deletes with no filter, deploys during a freeze or off-hours, spend that adds up over a day, and an actor firing off an unusually high rate of actions.",
    templates: [
      { policy_id: "velocity-deny-freeze-window", effect: "deny", priority: 11, action: "deploy.*", conditions: [{ field: "freeze", op: "eq", value: true }], description: "Deploys are blocked during an active change freeze window.", control: "Change-freeze guard" },
      { policy_id: "velocity-deny-freeze-migrate", effect: "deny", priority: 11, action: "db.migrate", conditions: [{ field: "freeze", op: "eq", value: true }], description: "Database migrations are blocked during an active change freeze window.", control: "Change-freeze guard" },
      { policy_id: "velocity-deny-delete-no-filter", effect: "deny", priority: 12, action: "db.delete", conditions: [{ field: "has_where", op: "eq", value: false }], description: "Blocks a delete that has no WHERE filter, which would wipe an entire table's rows.", control: "Destructive-action guard" },
      { policy_id: "velocity-approve-prod-deploy", effect: "require_approval", priority: 24, action: "deploy.*", approvals_required: 1, conditions: [{ field: "env", op: "eq", value: "prod" }], description: "Deploys to the production environment require human approval.", control: "Change-management control" },
      { policy_id: "velocity-approve-external-email", effect: "require_approval", priority: 26, action: "email.send", approvals_required: 1, conditions: [{ field: "recipient_domain", op: "not_in", value: ["yourcompany.com"] }], description: "Emails going to a domain outside the company require approval before sending. Admins: edit the allowed-domain list for your org.", control: "Data-egress control" },
      { policy_id: "velocity-approve-mass-email", effect: "require_approval", priority: 26, action: "email.send", approvals_required: 1, conditions: [{ field: "recipient_count", op: "gt", value: 25 }], description: "Emails going to more than 25 recipients at once require approval, to catch accidental or runaway mass sends.", control: "Mass-action guard" },
      { policy_id: "velocity-approve-daily-spend-cap", effect: "require_approval", priority: 26, action: "payment.*", approvals_required: 1, conditions: [{ field: "daily_total", op: "gt", value: 5000 }], description: "Once the organization's payment activity for the day totals more than $5,000, further payment actions require approval.", control: "Money-movement control" },
      { policy_id: "velocity-approve-off-hours", effect: "require_approval", priority: 27, action: "deploy.*", approvals_required: 1, conditions: [{ field: "off_hours", op: "eq", value: true }], description: "Deploys initiated outside normal business hours require human approval.", control: "Off-hours control" },
      { policy_id: "velocity-approve-high-frequency", effect: "require_approval", priority: 28, action: "*", approvals_required: 1, conditions: [{ field: "actor_action_count_1h", op: "gt", value: 100 }], description: "If an actor has taken more than 100 actions in the last hour, further actions require approval — catches a runaway or looping agent.", control: "Runaway-agent guard" },
    ],
  },
  {
    key: "email-comms",
    name: "Email & communications",
    framework: "Data egress",
    blurb: "Stops an agent from blasting outbound email, exporting contact lists, or auto-forwarding, and keeps mass or external sends behind a human.",
    templates: [
      { policy_id: "email-comms-approve-external", effect: "require_approval", priority: 26, action: "email.send", approvals_required: 1, conditions: [{ field: "recipient_domain", op: "not_in", value: ["yourcompany.com"] }], description: "Email to a domain outside the company requires approval. Admins: set your own allowed-domain list.", control: "Data-egress control" },
      { policy_id: "email-comms-approve-mass", effect: "require_approval", priority: 26, action: "email.send", approvals_required: 1, conditions: [{ field: "recipient_count", op: "gt", value: 25 }], description: "Sending to more than 25 recipients at once requires approval, to catch accidental mass sends.", control: "Mass-action guard" },
      { policy_id: "email-comms-deny-forwarding-rule", effect: "deny", priority: 10, action: "email.forwarding.create", description: "Creating an auto-forwarding rule via an agent is never allowed, a common data-exfiltration path.", control: "Exfiltration guard" },
      { policy_id: "email-comms-approve-distribution-list", effect: "require_approval", priority: 24, action: "email.distribution_list.send", approvals_required: 1, description: "Sending to a company distribution list requires approval.", control: "Mass-action guard" },
      { policy_id: "email-comms-approve-contact-export", effect: "require_approval", priority: 24, action: "contact.export", approvals_required: 1, description: "Exporting a contact or address list requires approval.", control: "Data-egress control" },
      { policy_id: "email-comms-deny-mailbox-delete", effect: "deny", priority: 11, action: "mailbox.delete", description: "Deleting a mailbox via an agent is never allowed.", control: "Destructive-action guard" },
      { policy_id: "email-comms-approve-calendar-external", effect: "require_approval", priority: 28, action: "calendar.invite.send", approvals_required: 1, conditions: [{ field: "external", op: "eq", value: true }], description: "Sending a calendar invite to external attendees requires approval.", control: "Data-egress control" },
      { policy_id: "email-comms-approve-autoresponder", effect: "require_approval", priority: 28, action: "email.autoresponder.set", approvals_required: 1, description: "Setting an automatic responder requires approval, to avoid leaking status or out-of-office details.", control: "Comms-integrity control" },
      { policy_id: "email-comms-deny-dmarc-weaken", effect: "deny", priority: 9, action: "email.dmarc.modify", description: "Weakening SPF, DKIM, or DMARC records via an agent is never allowed.", control: "Anti-spoofing guard" },
    ],
  },
  {
    key: "crm-sales",
    name: "CRM & sales",
    framework: "Customer-data safety",
    blurb: "Guards the customer database: no bulk deletes or exports, approvals on merges, mass campaigns, pricing, and closing deals.",
    templates: [
      { policy_id: "crm-sales-deny-bulk-delete", effect: "deny", priority: 11, action: "crm.bulk_delete", description: "Bulk-deleting CRM records via an agent is never allowed.", control: "Destructive-action guard" },
      { policy_id: "crm-sales-approve-record-delete", effect: "require_approval", priority: 24, action: "crm.record.delete", approvals_required: 1, description: "Deleting a CRM record requires human approval.", control: "Data-integrity control" },
      { policy_id: "crm-sales-approve-export", effect: "require_approval", priority: 24, action: "crm.export", approvals_required: 1, description: "Exporting CRM data requires approval.", control: "Data-egress control" },
      { policy_id: "crm-sales-approve-mass-email", effect: "require_approval", priority: 26, action: "crm.campaign.send", approvals_required: 1, description: "Sending a marketing campaign or mass email from the CRM requires approval.", control: "Mass-action guard" },
      { policy_id: "crm-sales-approve-merge", effect: "require_approval", priority: 24, action: "crm.record.merge", approvals_required: 1, description: "Merging CRM records requires approval, merges are hard to reverse.", control: "Data-integrity control" },
      { policy_id: "crm-sales-approve-opportunity-close", effect: "require_approval", priority: 28, action: "crm.opportunity.close", approvals_required: 1, description: "Closing or updating a sales opportunity stage requires approval.", control: "Revenue-integrity control" },
      { policy_id: "crm-sales-approve-quote", effect: "require_approval", priority: 28, action: "crm.quote.approve", approvals_required: 1, description: "Approving a customer quote requires human sign-off.", control: "Revenue-integrity control" },
      { policy_id: "crm-sales-approve-discount", effect: "require_approval", priority: 28, action: "crm.discount.apply", approvals_required: 1, conditions: [{ field: "percent", op: "gt", value: 20 }], description: "Applying a discount over 20% requires approval.", control: "Revenue-integrity control" },
      { policy_id: "crm-sales-approve-pricebook", effect: "require_approval", priority: 24, action: "crm.pricebook.update", approvals_required: 1, description: "Changing the price book requires approval.", control: "Revenue-integrity control" },
      { policy_id: "crm-sales-approve-workflow", effect: "require_approval", priority: 24, action: "crm.workflow.modify", approvals_required: 1, description: "Modifying a CRM automation or workflow requires approval.", control: "Change-management control" },
      { policy_id: "crm-sales-allow-read", effect: "allow", priority: 33, action: "crm.*.read", description: "Reading CRM records is allowed for any actor.", control: "Least-friction reads" },
    ],
  },
  {
    key: "support-helpdesk",
    name: "Support & helpdesk",
    framework: "Support-desk safety",
    blurb: "Keeps a support agent from issuing refunds, deleting accounts, exposing customer PII, or blasting canned replies without a human.",
    templates: [
      { policy_id: "support-helpdesk-approve-refund", effect: "require_approval", priority: 26, action: "support.refund.issue", approvals_required: 1, description: "Issuing a refund from the support desk requires approval.", control: "Money-movement control" },
      { policy_id: "support-helpdesk-approve-account-delete", effect: "require_approval", priority: 24, action: "support.account.delete", approvals_required: 1, description: "Deleting a customer account from support requires approval.", control: "Destructive-action control" },
      { policy_id: "support-helpdesk-approve-bulk-close", effect: "require_approval", priority: 28, action: "support.ticket.bulk_close", approvals_required: 1, description: "Bulk-closing tickets requires approval, to catch a runaway automation.", control: "Mass-action guard" },
      { policy_id: "support-helpdesk-approve-mass-reply", effect: "require_approval", priority: 26, action: "support.macro.mass_apply", approvals_required: 1, description: "Applying a canned reply across many tickets at once requires approval.", control: "Mass-action guard" },
      { policy_id: "support-helpdesk-approve-pii-export", effect: "require_approval", priority: 24, action: "support.pii.export", approvals_required: 1, description: "Exporting customer PII from the support tool requires approval.", control: "Data-egress control" },
      { policy_id: "support-helpdesk-deny-impersonate", effect: "deny", priority: 10, action: "support.user.impersonate", description: "An agent logging in as a customer via support impersonation is never allowed.", control: "Identity guard" },
      { policy_id: "support-helpdesk-approve-merge", effect: "require_approval", priority: 24, action: "support.user.merge", approvals_required: 1, description: "Merging two customer profiles requires approval.", control: "Data-integrity control" },
      { policy_id: "support-helpdesk-approve-broadcast", effect: "require_approval", priority: 26, action: "support.chat.broadcast", approvals_required: 1, description: "Broadcasting a message to all live-chat visitors requires approval.", control: "Mass-action guard" },
      { policy_id: "support-helpdesk-approve-sla-modify", effect: "require_approval", priority: 28, action: "support.sla.modify", approvals_required: 1, description: "Changing an SLA policy requires approval.", control: "Change-management control" },
      { policy_id: "support-helpdesk-allow-read", effect: "allow", priority: 33, action: "support.ticket.read", description: "Reading support tickets is allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "cloud-iam",
    name: "Cloud IAM & security (AWS / GCP / Azure)",
    framework: "Cloud security",
    blurb: "The cloud blast-radius controls: no public buckets, open security groups, disabled audit trails, or root access, and approvals on IAM and resource deletes.",
    templates: [
      { policy_id: "cloud-iam-deny-s3-public", effect: "deny", priority: 9, action: "cloud.storage.make_public", description: "Making a storage bucket or blob publicly readable via an agent is never allowed.", control: "Data-exposure guard" },
      { policy_id: "cloud-iam-deny-sg-open", effect: "deny", priority: 9, action: "cloud.security_group.open", conditions: [{ field: "cidr", op: "eq", value: "0.0.0.0/0" }], description: "Opening a security-group rule to the whole internet (0.0.0.0/0) is never allowed.", control: "Network-exposure guard" },
      { policy_id: "cloud-iam-deny-cloudtrail-disable", effect: "deny", priority: 8, action: "cloud.audit_log.disable", description: "Disabling the cloud audit trail (CloudTrail, Cloud Audit Logs) is never allowed.", control: "Audit-integrity guard" },
      { policy_id: "cloud-iam-deny-root-access", effect: "deny", priority: 8, action: "cloud.root.access", description: "Using the cloud root or global-admin account via an agent is never allowed.", control: "Privileged-access guard" },
      { policy_id: "cloud-iam-approve-iam-policy", effect: "require_approval", priority: 22, action: "cloud.iam.policy.attach", approvals_required: 1, description: "Attaching or changing an IAM policy requires human approval.", control: "Access-control change" },
      { policy_id: "cloud-iam-approve-iam-key", effect: "require_approval", priority: 22, action: "cloud.iam.key.create", approvals_required: 1, description: "Creating a long-lived IAM access key requires approval.", control: "Secrets control" },
      { policy_id: "cloud-iam-approve-resource-delete", effect: "require_approval", priority: 24, action: "cloud.resource.delete", approvals_required: 1, description: "Deleting a cloud resource requires human approval.", control: "Destructive-action control" },
      { policy_id: "cloud-iam-deny-snapshot-delete", effect: "deny", priority: 12, action: "cloud.snapshot.delete", description: "Deleting a backup snapshot or AMI via an agent is never allowed.", control: "Data-recovery guard" },
      { policy_id: "cloud-iam-approve-instance-terminate", effect: "require_approval", priority: 24, action: "cloud.instance.terminate", approvals_required: 1, description: "Terminating a compute instance requires approval.", control: "Operational-safety control" },
      { policy_id: "cloud-iam-deny-kms-delete", effect: "deny", priority: 8, action: "cloud.kms.key.schedule_delete", description: "Scheduling deletion of a KMS key is never allowed, it can render data permanently unreadable.", control: "Cryptographic-material guard" },
      { policy_id: "cloud-iam-approve-billing", effect: "require_approval", priority: 26, action: "cloud.billing.modify", approvals_required: 1, description: "Changing billing or spend limits requires approval.", control: "Cost-control" },
      { policy_id: "cloud-iam-allow-describe", effect: "allow", priority: 33, action: "cloud.*.describe", description: "Read-only describe and list calls are allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "source-control",
    name: "Source control (GitHub / GitLab)",
    framework: "Code & repo safety",
    blurb: "Protects the codebase: no repo deletes, force-pushes to main, public exposure, or committed secrets, with approvals on releases and access.",
    templates: [
      { policy_id: "source-control-deny-repo-delete", effect: "deny", priority: 10, action: "vcs.repo.delete", description: "Deleting a repository via an agent is never allowed.", control: "Destructive-action guard" },
      { policy_id: "source-control-deny-repo-public", effect: "deny", priority: 9, action: "vcs.repo.visibility.set", conditions: [{ field: "visibility", op: "eq", value: "public" }], description: "Making a private repository public via an agent is never allowed.", control: "Data-exposure guard" },
      { policy_id: "source-control-deny-force-push-main", effect: "deny", priority: 10, action: "vcs.branch.force_push", resource: "branch:main", description: "Force-pushing to the main branch is never allowed, it rewrites shared history.", control: "History-integrity guard" },
      { policy_id: "source-control-deny-secret-commit", effect: "deny", priority: 8, action: "vcs.secret.commit", description: "Committing a detected secret or credential is never allowed.", control: "Secrets guard" },
      { policy_id: "source-control-approve-branch-protection", effect: "require_approval", priority: 22, action: "vcs.branch_protection.modify", approvals_required: 1, description: "Changing branch-protection rules requires approval.", control: "Change-management control" },
      { policy_id: "source-control-approve-member-add", effect: "require_approval", priority: 24, action: "vcs.member.add", approvals_required: 1, description: "Adding a collaborator to a repo or org requires approval.", control: "Access-control change" },
      { policy_id: "source-control-approve-deploy-key", effect: "require_approval", priority: 22, action: "vcs.deploy_key.add", approvals_required: 1, description: "Adding a deploy key or machine credential requires approval.", control: "Secrets control" },
      { policy_id: "source-control-approve-workflow-modify", effect: "require_approval", priority: 22, action: "vcs.workflow.modify", approvals_required: 1, description: "Modifying a CI workflow file requires approval, workflows run with repo secrets.", control: "Supply-chain control" },
      { policy_id: "source-control-approve-release", effect: "require_approval", priority: 26, action: "vcs.release.publish", approvals_required: 1, description: "Publishing a release requires approval.", control: "Change-management control" },
      { policy_id: "source-control-approve-package-publish", effect: "require_approval", priority: 26, action: "vcs.package.publish", approvals_required: 1, description: "Publishing a package to a registry requires approval.", control: "Supply-chain control" },
      { policy_id: "source-control-deny-repo-transfer", effect: "deny", priority: 10, action: "vcs.repo.transfer", description: "Transferring a repository to another owner via an agent is never allowed.", control: "Ownership guard" },
      { policy_id: "source-control-approve-webhook", effect: "require_approval", priority: 24, action: "vcs.webhook.add", approvals_required: 1, description: "Adding a repo webhook requires approval, webhooks can leak payloads.", control: "Data-egress control" },
    ],
  },
  {
    key: "cicd",
    name: "CI/CD & releases",
    framework: "Pipeline safety",
    blurb: "Keeps an agent from tampering with the build pipeline: no reading CI secrets, bypassing approvals, or self-registering runners, and approvals on production deploys.",
    templates: [
      { policy_id: "cicd-deny-secret-read", effect: "deny", priority: 9, action: "ci.secret.read", description: "Reading CI/CD pipeline secrets via an agent is never allowed.", control: "Secrets guard" },
      { policy_id: "cicd-deny-approval-bypass", effect: "deny", priority: 8, action: "ci.approval.bypass", description: "Bypassing a required pipeline approval gate is never allowed.", control: "Change-control guard" },
      { policy_id: "cicd-approve-prod-deploy", effect: "require_approval", priority: 24, action: "ci.deploy", approvals_required: 1, conditions: [{ field: "env", op: "eq", value: "prod" }], description: "Deploying to production requires human approval.", control: "Change-management control" },
      { policy_id: "cicd-approve-pipeline-modify", effect: "require_approval", priority: 22, action: "ci.pipeline.modify", approvals_required: 1, description: "Modifying the pipeline definition requires approval.", control: "Supply-chain control" },
      { policy_id: "cicd-approve-runner-register", effect: "require_approval", priority: 22, action: "ci.runner.register", approvals_required: 1, description: "Registering a new build runner requires approval, runners execute untrusted code with secrets.", control: "Supply-chain control" },
      { policy_id: "cicd-approve-env-modify", effect: "require_approval", priority: 22, action: "ci.env.modify", approvals_required: 1, description: "Changing a protected environment or its variables requires approval.", control: "Change-management control" },
      { policy_id: "cicd-approve-protected-var", effect: "require_approval", priority: 22, action: "ci.variable.protected.modify", approvals_required: 1, description: "Modifying a protected CI variable requires approval.", control: "Secrets control" },
      { policy_id: "cicd-deny-artifact-delete", effect: "deny", priority: 12, action: "ci.artifact.delete", description: "Deleting build artifacts or their signatures via an agent is never allowed.", control: "Provenance guard" },
      { policy_id: "cicd-approve-schedule-modify", effect: "require_approval", priority: 26, action: "ci.schedule.modify", approvals_required: 1, description: "Changing a pipeline schedule requires approval.", control: "Change-management control" },
      { policy_id: "cicd-deny-freeze-deploy", effect: "deny", priority: 11, action: "ci.deploy", conditions: [{ field: "freeze", op: "eq", value: true }], description: "Deploys are blocked during an active change freeze window.", control: "Change-freeze guard" },
    ],
  },
  {
    key: "kubernetes",
    name: "Kubernetes & containers",
    framework: "Orchestration safety",
    blurb: "Cluster guardrails: no namespace deletes, secret reads, or pod exec, and approvals on RBAC, scaling, and node drains.",
    templates: [
      { policy_id: "kubernetes-deny-namespace-delete", effect: "deny", priority: 11, action: "k8s.namespace.delete", description: "Deleting a namespace via an agent is never allowed, it removes everything inside it.", control: "Destructive-action guard" },
      { policy_id: "kubernetes-deny-secret-read", effect: "deny", priority: 9, action: "k8s.secret.read", description: "Reading Kubernetes secrets via an agent is never allowed.", control: "Secrets guard" },
      { policy_id: "kubernetes-approve-pod-exec", effect: "require_approval", priority: 22, action: "k8s.pod.exec", approvals_required: 1, description: "Executing a shell inside a running pod requires approval.", control: "Privileged-access control" },
      { policy_id: "kubernetes-approve-rbac", effect: "require_approval", priority: 22, action: "k8s.rbac.modify", approvals_required: 1, description: "Changing RBAC roles or bindings requires approval.", control: "Access-control change" },
      { policy_id: "kubernetes-approve-scale", effect: "require_approval", priority: 26, action: "k8s.deployment.scale", approvals_required: 1, conditions: [{ field: "replicas", op: "eq", value: 0 }], description: "Scaling a deployment to zero replicas requires approval, it takes the service offline.", control: "Operational-safety control" },
      { policy_id: "kubernetes-approve-node-drain", effect: "require_approval", priority: 24, action: "k8s.node.drain", approvals_required: 1, description: "Draining a node requires approval.", control: "Operational-safety control" },
      { policy_id: "kubernetes-deny-pvc-delete", effect: "deny", priority: 12, action: "k8s.pvc.delete", description: "Deleting a persistent volume claim via an agent is never allowed, it can destroy stored data.", control: "Data-recovery guard" },
      { policy_id: "kubernetes-approve-crd-delete", effect: "require_approval", priority: 24, action: "k8s.crd.delete", approvals_required: 1, description: "Deleting a custom resource definition requires approval.", control: "Destructive-action control" },
      { policy_id: "kubernetes-approve-ingress-modify", effect: "require_approval", priority: 24, action: "k8s.ingress.modify", approvals_required: 1, description: "Changing ingress or gateway routing requires approval.", control: "Network-change control" },
      { policy_id: "kubernetes-allow-get", effect: "allow", priority: 33, action: "k8s.*.get", description: "Read-only get and list calls are allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "data-warehouse",
    name: "Data warehouse (Snowflake / BigQuery)",
    framework: "Analytics-data safety",
    blurb: "Protects the warehouse: no dropped tables, unloads to external storage, or disabled masking, and approvals on grants and shares.",
    templates: [
      { policy_id: "data-warehouse-deny-table-drop", effect: "deny", priority: 11, action: "dw.table.drop", description: "Dropping a warehouse table via an agent is never allowed.", control: "Destructive-action guard" },
      { policy_id: "data-warehouse-deny-unload-external", effect: "deny", priority: 10, action: "dw.unload_external", description: "Unloading warehouse data to an external stage or bucket via an agent is never allowed.", control: "Data-egress guard" },
      { policy_id: "data-warehouse-deny-masking-disable", effect: "deny", priority: 9, action: "dw.masking.disable", description: "Disabling a dynamic data-masking policy is never allowed.", control: "Privacy-control guard" },
      { policy_id: "data-warehouse-approve-export", effect: "require_approval", priority: 24, action: "dw.data.export", approvals_required: 1, description: "Exporting warehouse data requires approval.", control: "Data-egress control" },
      { policy_id: "data-warehouse-approve-grant", effect: "require_approval", priority: 22, action: "dw.grant", approvals_required: 1, description: "Granting a warehouse privilege or role requires approval.", control: "Access-control change" },
      { policy_id: "data-warehouse-approve-share", effect: "require_approval", priority: 24, action: "dw.share.create", approvals_required: 1, description: "Creating a data share with another account requires approval.", control: "Data-egress control" },
      { policy_id: "data-warehouse-approve-pipe-modify", effect: "require_approval", priority: 24, action: "dw.pipe.modify", approvals_required: 1, description: "Modifying an ingestion pipe or scheduled load requires approval.", control: "Change-management control" },
      { policy_id: "data-warehouse-approve-clone", effect: "require_approval", priority: 26, action: "dw.database.clone", approvals_required: 1, description: "Cloning a database or schema requires approval, clones can duplicate sensitive data.", control: "Data-sprawl control" },
      { policy_id: "data-warehouse-approve-warehouse-resize", effect: "require_approval", priority: 28, action: "dw.warehouse.resize", approvals_required: 1, description: "Resizing a warehouse up requires approval, it drives compute cost.", control: "Cost-control" },
      { policy_id: "data-warehouse-allow-select", effect: "allow", priority: 33, action: "dw.query.select", description: "Read-only SELECT queries are allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "database-admin",
    name: "Database administration (extended)",
    framework: "Data safety",
    blurb: "Deeper database guardrails beyond the basics: mass updates without a filter, dropped indexes and views, replication and read-only changes, and grants.",
    templates: [
      { policy_id: "database-admin-deny-mass-update", effect: "deny", priority: 12, action: "db.update", conditions: [{ field: "has_where", op: "eq", value: false }], description: "Blocks an UPDATE with no WHERE filter, which would rewrite every row in a table.", control: "Destructive-action guard" },
      { policy_id: "database-admin-approve-grant", effect: "require_approval", priority: 22, action: "db.user.grant", approvals_required: 1, description: "Granting database privileges requires approval.", control: "Access-control change" },
      { policy_id: "database-admin-deny-readonly-disable", effect: "deny", priority: 10, action: "db.readonly.disable", description: "Disabling read-only mode on a replica or reporting database via an agent is never allowed.", control: "Data-integrity guard" },
      { policy_id: "database-admin-approve-replication", effect: "require_approval", priority: 24, action: "db.replication.modify", approvals_required: 1, description: "Changing replication settings requires approval.", control: "Availability control" },
      { policy_id: "database-admin-approve-index-drop", effect: "require_approval", priority: 24, action: "db.index.drop", approvals_required: 1, description: "Dropping an index requires approval, it can degrade production performance.", control: "Performance control" },
      { policy_id: "database-admin-deny-view-drop", effect: "deny", priority: 13, action: "db.view.drop", description: "Dropping a database view via an agent is never allowed.", control: "Destructive-action guard" },
      { policy_id: "database-admin-approve-trigger-modify", effect: "require_approval", priority: 24, action: "db.trigger.modify", approvals_required: 1, description: "Modifying a database trigger requires approval.", control: "Change-management control" },
      { policy_id: "database-admin-approve-extension-install", effect: "require_approval", priority: 24, action: "db.extension.install", approvals_required: 1, description: "Installing a database extension requires approval.", control: "Supply-chain control" },
      { policy_id: "database-admin-approve-connection-modify", effect: "require_approval", priority: 26, action: "db.connection_limit.modify", approvals_required: 1, description: "Changing connection limits or pooling requires approval.", control: "Availability control" },
      { policy_id: "database-admin-deny-backup-disable", effect: "deny", priority: 9, action: "db.backup.disable", description: "Disabling automated database backups via an agent is never allowed.", control: "Data-recovery guard" },
      { policy_id: "database-admin-allow-explain", effect: "allow", priority: 33, action: "db.query.explain", description: "Read-only EXPLAIN and query-plan calls are allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "collaboration",
    name: "Collaboration (Slack / Teams)",
    framework: "Workspace safety",
    blurb: "Keeps an agent from archiving channels, turning on external sharing, mass-DMing, or exporting workspace data.",
    templates: [
      { policy_id: "collaboration-deny-channel-delete", effect: "deny", priority: 12, action: "chat.channel.delete", description: "Deleting a channel via an agent is never allowed, its history is lost.", control: "Destructive-action guard" },
      { policy_id: "collaboration-approve-channel-archive", effect: "require_approval", priority: 26, action: "chat.channel.archive", approvals_required: 1, description: "Archiving a channel requires approval.", control: "Change-management control" },
      { policy_id: "collaboration-deny-external-share", effect: "deny", priority: 10, action: "chat.external_share.enable", description: "Enabling external or cross-org sharing on a channel via an agent is never allowed.", control: "Data-egress guard" },
      { policy_id: "collaboration-approve-webhook", effect: "require_approval", priority: 24, action: "chat.webhook.create", approvals_required: 1, description: "Creating an incoming or outgoing webhook requires approval.", control: "Data-egress control" },
      { policy_id: "collaboration-approve-admin-grant", effect: "require_approval", priority: 22, action: "chat.admin.grant", approvals_required: 1, description: "Granting workspace-admin rights requires approval.", control: "Access-control change" },
      { policy_id: "collaboration-approve-mass-dm", effect: "require_approval", priority: 26, action: "chat.mass_dm", approvals_required: 1, conditions: [{ field: "recipient_count", op: "gt", value: 20 }], description: "Direct-messaging more than 20 people at once requires approval.", control: "Mass-action guard" },
      { policy_id: "collaboration-approve-app-install", effect: "require_approval", priority: 24, action: "chat.app.install", approvals_required: 1, description: "Installing a third-party app or bot requires approval.", control: "Supply-chain control" },
      { policy_id: "collaboration-approve-data-export", effect: "require_approval", priority: 24, action: "chat.data.export", approvals_required: 1, description: "Exporting workspace messages or files requires approval.", control: "Data-egress control" },
      { policy_id: "collaboration-approve-retention", effect: "require_approval", priority: 24, action: "chat.retention.modify", approvals_required: 1, description: "Changing message-retention settings requires approval.", control: "Records-retention control" },
      { policy_id: "collaboration-approve-guest-invite", effect: "require_approval", priority: 28, action: "chat.guest.invite", approvals_required: 1, description: "Inviting an external guest to the workspace requires approval.", control: "Access-control change" },
    ],
  },
  {
    key: "hr-people",
    name: "HR & people ops",
    framework: "Employee-data safety",
    blurb: "Guards the most sensitive records in the company: no agent terminating staff, changing pay or bank details, or exporting employee PII without a human.",
    templates: [
      { policy_id: "hr-people-deny-terminate", effect: "deny", priority: 10, action: "hr.employee.terminate", description: "Terminating an employee via an agent is never allowed.", control: "People-safety guard" },
      { policy_id: "hr-people-deny-bank-change", effect: "deny", priority: 9, action: "hr.bank_details.change", description: "Changing an employee's payroll bank details via an agent is never allowed, a common payroll-fraud path.", control: "Payroll-fraud guard" },
      { policy_id: "hr-people-approve-comp-change", effect: "require_approval", priority: 22, action: "hr.comp.change", approvals_required: 1, description: "Changing compensation requires human approval.", control: "Financial-control" },
      { policy_id: "hr-people-approve-pii-export", effect: "require_approval", priority: 22, action: "hr.pii.export", approvals_required: 1, description: "Exporting employee personal data requires approval.", control: "Data-egress control" },
      { policy_id: "hr-people-approve-payroll-run", effect: "require_approval", priority: 24, action: "hr.payroll.run", approvals_required: 1, description: "Running payroll requires human approval.", control: "Money-movement control" },
      { policy_id: "hr-people-approve-offer-send", effect: "require_approval", priority: 26, action: "hr.offer.send", approvals_required: 1, description: "Sending an offer letter requires approval.", control: "Commitment-control" },
      { policy_id: "hr-people-approve-benefit-modify", effect: "require_approval", priority: 26, action: "hr.benefit.modify", approvals_required: 1, description: "Changing benefits enrollment requires approval.", control: "Financial-control" },
      { policy_id: "hr-people-deny-record-delete", effect: "deny", priority: 12, action: "hr.record.delete", description: "Deleting an employee record via an agent is never allowed, records have legal retention.", control: "Records-retention guard" },
      { policy_id: "hr-people-approve-background-check", effect: "require_approval", priority: 28, action: "hr.background_check.order", approvals_required: 1, description: "Ordering a background check requires approval, it triggers consent and cost.", control: "Compliance-control" },
      { policy_id: "hr-people-approve-mass-message", effect: "require_approval", priority: 26, action: "hr.mass_message", approvals_required: 1, description: "Sending a message to all employees requires approval.", control: "Mass-action guard" },
      { policy_id: "hr-people-approve-title-change", effect: "require_approval", priority: 28, action: "hr.title.change", approvals_required: 1, description: "Changing an employee's title or manager requires approval.", control: "Change-management control" },
    ],
  },
  {
    key: "finance-accounting",
    name: "Finance & accounting",
    framework: "Financial controls",
    blurb: "Segregation-of-duties for the books and the bank: approvals on journal entries, invoices, POs, and wires, and a lock on vendor bank changes.",
    templates: [
      { policy_id: "finance-accounting-deny-vendor-bank-change", effect: "deny", priority: 9, action: "fin.vendor.bank.change", description: "Changing a vendor's payout bank details via an agent is never allowed, the top invoice-fraud vector.", control: "Payment-fraud guard" },
      { policy_id: "finance-accounting-approve-wire", effect: "require_approval", priority: 24, action: "fin.wire.send", approvals_required: 1, description: "Sending a wire transfer requires human approval.", control: "Money-movement control" },
      { policy_id: "finance-accounting-deny-wire-ceiling", effect: "deny", priority: 14, action: "fin.wire.send", conditions: [{ field: "amount", op: "gt", value: 50000 }], description: "Hard ceiling: wires over $50,000 are never auto-run by an agent, regardless of any approval tier.", control: "Money-movement ceiling" },
      { policy_id: "finance-accounting-approve-journal", effect: "require_approval", priority: 24, action: "fin.journal.post", approvals_required: 1, description: "Posting a journal entry requires approval.", control: "Books-integrity control" },
      { policy_id: "finance-accounting-approve-vendor-create", effect: "require_approval", priority: 24, action: "fin.vendor.create", approvals_required: 1, description: "Adding a new vendor requires approval, new vendors enable fraudulent payments.", control: "Vendor-control" },
      { policy_id: "finance-accounting-approve-invoice", effect: "require_approval", priority: 26, action: "fin.invoice.approve", approvals_required: 1, description: "Approving a vendor invoice for payment requires human sign-off.", control: "Money-movement control" },
      { policy_id: "finance-accounting-approve-po", effect: "require_approval", priority: 26, action: "fin.po.approve", approvals_required: 1, description: "Approving a purchase order requires approval.", control: "Commitment-control" },
      { policy_id: "finance-accounting-approve-expense", effect: "require_approval", priority: 28, action: "fin.expense.approve", approvals_required: 1, conditions: [{ field: "amount", op: "gt", value: 500 }], description: "Approving an expense report over $500 requires approval.", control: "Money-movement control" },
      { policy_id: "finance-accounting-deny-ledger-close-reopen", effect: "deny", priority: 11, action: "fin.ledger.reopen", description: "Reopening a closed accounting period via an agent is never allowed.", control: "Books-integrity guard" },
      { policy_id: "finance-accounting-approve-tax-file", effect: "require_approval", priority: 24, action: "fin.tax.file", approvals_required: 1, description: "Filing a tax return or remittance requires approval.", control: "Compliance-control" },
      { policy_id: "finance-accounting-approve-gl-export", effect: "require_approval", priority: 26, action: "fin.gl.export", approvals_required: 1, description: "Exporting the general ledger requires approval.", control: "Data-egress control" },
      { policy_id: "finance-accounting-approve-budget-modify", effect: "require_approval", priority: 28, action: "fin.budget.modify", approvals_required: 1, description: "Changing a budget requires approval.", control: "Change-management control" },
    ],
  },
  {
    key: "marketing-ads",
    name: "Marketing & ad spend",
    framework: "Spend & brand safety",
    blurb: "Caps ad budget changes, puts a human on publishing campaigns and mass sends, and protects audience exports and tracking.",
    templates: [
      { policy_id: "marketing-ads-approve-budget-change", effect: "require_approval", priority: 24, action: "ads.budget.change", approvals_required: 1, description: "Changing an ad campaign budget requires approval.", control: "Spend-control" },
      { policy_id: "marketing-ads-deny-daily-spend-ceiling", effect: "deny", priority: 14, action: "ads.budget.change", conditions: [{ field: "daily_budget", op: "gt", value: 5000 }], description: "Hard ceiling: an agent can never set a daily ad budget above $5,000.", control: "Spend ceiling" },
      { policy_id: "marketing-ads-approve-campaign-publish", effect: "require_approval", priority: 26, action: "ads.campaign.publish", approvals_required: 1, description: "Publishing or launching a campaign requires approval.", control: "Brand-safety control" },
      { policy_id: "marketing-ads-approve-audience-export", effect: "require_approval", priority: 24, action: "ads.audience.export", approvals_required: 1, description: "Exporting an audience or customer-match list requires approval.", control: "Data-egress control" },
      { policy_id: "marketing-ads-approve-creative-publish", effect: "require_approval", priority: 26, action: "ads.creative.publish", approvals_required: 1, description: "Publishing new ad creative requires approval.", control: "Brand-safety control" },
      { policy_id: "marketing-ads-approve-account-access", effect: "require_approval", priority: 22, action: "ads.account.access.grant", approvals_required: 1, description: "Granting access to an ad account requires approval.", control: "Access-control change" },
      { policy_id: "marketing-ads-approve-bid-modify", effect: "require_approval", priority: 28, action: "ads.bid.modify", approvals_required: 1, description: "Changing bid strategy requires approval.", control: "Spend-control" },
      { policy_id: "marketing-ads-approve-pixel-modify", effect: "require_approval", priority: 24, action: "ads.pixel.modify", approvals_required: 1, description: "Changing a tracking pixel or conversion tag requires approval.", control: "Privacy-control" },
      { policy_id: "marketing-ads-approve-mass-email", effect: "require_approval", priority: 26, action: "ads.email.send", approvals_required: 1, conditions: [{ field: "recipient_count", op: "gt", value: 100 }], description: "Sending a marketing email to more than 100 recipients requires approval.", control: "Mass-action guard" },
      { policy_id: "marketing-ads-approve-social-publish", effect: "require_approval", priority: 26, action: "social.post.publish", approvals_required: 1, description: "Publishing a post to a company social account requires approval.", control: "Brand-safety control" },
    ],
  },
  {
    key: "ecommerce",
    name: "E-commerce & storefront (Shopify)",
    framework: "Storefront safety",
    blurb: "Protects the store: approvals on price changes, discounts, refunds, and payout settings, and a lock on customer-list exports and theme publishing.",
    templates: [
      { policy_id: "ecommerce-approve-price-change", effect: "require_approval", priority: 24, action: "shop.product.price.change", approvals_required: 1, description: "Changing a product price requires approval.", control: "Revenue-integrity control" },
      { policy_id: "ecommerce-approve-discount-create", effect: "require_approval", priority: 26, action: "shop.discount.create", approvals_required: 1, conditions: [{ field: "percent", op: "gt", value: 25 }], description: "Creating a discount over 25% requires approval.", control: "Revenue-integrity control" },
      { policy_id: "ecommerce-approve-order-refund", effect: "require_approval", priority: 26, action: "shop.order.refund", approvals_required: 1, description: "Refunding an order requires approval.", control: "Money-movement control" },
      { policy_id: "ecommerce-approve-order-cancel", effect: "require_approval", priority: 28, action: "shop.order.cancel", approvals_required: 1, description: "Cancelling an order requires approval.", control: "Fulfillment control" },
      { policy_id: "ecommerce-deny-customer-export", effect: "deny", priority: 11, action: "shop.customer.export", description: "Exporting the full customer list via an agent is never allowed.", control: "Data-egress guard" },
      { policy_id: "ecommerce-approve-inventory-set", effect: "require_approval", priority: 28, action: "shop.inventory.set", approvals_required: 1, conditions: [{ field: "quantity", op: "eq", value: 0 }], description: "Setting inventory to zero requires approval, it hides a product from sale.", control: "Availability control" },
      { policy_id: "ecommerce-approve-theme-publish", effect: "require_approval", priority: 24, action: "shop.theme.publish", approvals_required: 1, description: "Publishing a storefront theme requires approval.", control: "Change-management control" },
      { policy_id: "ecommerce-deny-payout-modify", effect: "deny", priority: 9, action: "shop.payout.modify", description: "Changing the store's payout bank account via an agent is never allowed.", control: "Payment-fraud guard" },
      { policy_id: "ecommerce-approve-app-install", effect: "require_approval", priority: 24, action: "shop.app.install", approvals_required: 1, description: "Installing a storefront app requires approval.", control: "Supply-chain control" },
      { policy_id: "ecommerce-approve-tax-modify", effect: "require_approval", priority: 26, action: "shop.tax.modify", approvals_required: 1, description: "Changing tax settings requires approval.", control: "Compliance-control" },
      { policy_id: "ecommerce-allow-read", effect: "allow", priority: 33, action: "shop.*.read", description: "Reading products, orders, and inventory is allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "legal-contracts",
    name: "Legal & contracts",
    framework: "Legal-commitment safety",
    blurb: "Keeps an agent from signing or executing anything binding, waiving rights, or deleting legal records, with approvals on filings and settlements.",
    templates: [
      { policy_id: "legal-contracts-deny-execute", effect: "deny", priority: 9, action: "legal.contract.execute", description: "Executing or countersigning a contract via an agent is never allowed.", control: "Binding-commitment guard" },
      { policy_id: "legal-contracts-approve-signature-request", effect: "require_approval", priority: 24, action: "legal.signature.request", approvals_required: 1, description: "Sending a document out for signature requires approval.", control: "Commitment-control" },
      { policy_id: "legal-contracts-deny-nda-waive", effect: "deny", priority: 10, action: "legal.nda.waive", description: "Waiving an NDA or confidentiality obligation via an agent is never allowed.", control: "Confidentiality guard" },
      { policy_id: "legal-contracts-deny-ip-assign", effect: "deny", priority: 10, action: "legal.ip.assign", description: "Assigning or transferring intellectual property via an agent is never allowed.", control: "IP-protection guard" },
      { policy_id: "legal-contracts-deny-record-delete", effect: "deny", priority: 11, action: "legal.record.delete", description: "Deleting a legal record via an agent is never allowed, records are under legal hold and retention.", control: "Records-retention guard" },
      { policy_id: "legal-contracts-approve-clause-modify", effect: "require_approval", priority: 26, action: "legal.clause.modify", approvals_required: 1, description: "Editing a contract clause requires approval.", control: "Change-management control" },
      { policy_id: "legal-contracts-approve-settlement", effect: "require_approval", priority: 22, action: "legal.dispute.settle", approvals_required: 1, description: "Settling a dispute or claim requires approval.", control: "Commitment-control" },
      { policy_id: "legal-contracts-deny-privilege-waive", effect: "deny", priority: 9, action: "legal.privilege.waive", description: "Waiving attorney-client privilege via an agent is never allowed.", control: "Privilege guard" },
      { policy_id: "legal-contracts-approve-filing", effect: "require_approval", priority: 24, action: "legal.filing.submit", approvals_required: 1, description: "Submitting a regulatory or court filing requires approval.", control: "Compliance-control" },
      { policy_id: "legal-contracts-approve-retention-modify", effect: "require_approval", priority: 24, action: "legal.retention.modify", approvals_required: 1, description: "Changing a records-retention or legal-hold setting requires approval.", control: "Records-retention control" },
    ],
  },
  {
    key: "directory-identity",
    name: "Directory & SSO (Okta / Entra / Google)",
    framework: "Identity provider safety",
    blurb: "Protects the identity provider itself: no MFA resets or admin grants, and approvals on deprovisioning, group changes, and federation.",
    templates: [
      { policy_id: "directory-identity-deny-mfa-reset", effect: "deny", priority: 9, action: "idp.mfa.reset", description: "Resetting a user's MFA via an agent is never allowed, it enables account takeover.", control: "Authentication guard" },
      { policy_id: "directory-identity-deny-admin-grant", effect: "deny", priority: 8, action: "idp.admin.grant", description: "Granting a super-admin or directory-admin role via an agent is never allowed.", control: "Privileged-access guard" },
      { policy_id: "directory-identity-approve-deprovision", effect: "require_approval", priority: 22, action: "idp.user.deprovision", approvals_required: 1, description: "Deprovisioning a user requires approval, it cuts all their access at once.", control: "Access-control change" },
      { policy_id: "directory-identity-approve-group-membership", effect: "require_approval", priority: 24, action: "idp.group.membership.modify", approvals_required: 1, description: "Changing group membership requires approval, groups drive app access.", control: "Access-control change" },
      { policy_id: "directory-identity-approve-app-assign", effect: "require_approval", priority: 24, action: "idp.app.assign", approvals_required: 1, description: "Assigning an application to a user or group requires approval.", control: "Access-control change" },
      { policy_id: "directory-identity-approve-password-reset", effect: "require_approval", priority: 26, action: "idp.password.reset", approvals_required: 1, description: "Forcing a password reset requires approval.", control: "Authentication control" },
      { policy_id: "directory-identity-approve-policy-modify", effect: "require_approval", priority: 22, action: "idp.policy.modify", approvals_required: 1, description: "Changing a sign-on, MFA, or conditional-access policy requires approval.", control: "Security-settings control" },
      { policy_id: "directory-identity-deny-federation-modify", effect: "deny", priority: 9, action: "idp.federation.modify", description: "Changing SSO federation or trust settings via an agent is never allowed.", control: "Trust-boundary guard" },
      { policy_id: "directory-identity-approve-provisioning-modify", effect: "require_approval", priority: 24, action: "idp.provisioning.modify", approvals_required: 1, description: "Changing automated user provisioning rules requires approval.", control: "Change-management control" },
      { policy_id: "directory-identity-approve-session-revoke", effect: "require_approval", priority: 28, action: "idp.session.revoke_all", approvals_required: 1, description: "Revoking all active sessions org-wide requires approval.", control: "Availability control" },
      { policy_id: "directory-identity-approve-user-suspend", effect: "require_approval", priority: 26, action: "idp.user.suspend", approvals_required: 1, description: "Suspending a user account requires approval.", control: "Access-control change" },
    ],
  },
  {
    key: "endpoint-device",
    name: "Endpoint & device management (MDM)",
    framework: "Device safety",
    blurb: "Stops an agent from wiping devices, disabling antivirus or encryption, or unenrolling endpoints, with approvals on config pushes.",
    templates: [
      { policy_id: "endpoint-device-deny-wipe", effect: "deny", priority: 8, action: "mdm.device.wipe", description: "Remotely wiping a device via an agent is never allowed.", control: "Destructive-action guard" },
      { policy_id: "endpoint-device-deny-av-disable", effect: "deny", priority: 9, action: "mdm.av.disable", description: "Disabling antivirus or endpoint protection via an agent is never allowed.", control: "Security-control guard" },
      { policy_id: "endpoint-device-deny-encryption-disable", effect: "deny", priority: 9, action: "mdm.encryption.disable", description: "Disabling disk encryption via an agent is never allowed.", control: "Data-protection guard" },
      { policy_id: "endpoint-device-approve-unenroll", effect: "require_approval", priority: 24, action: "mdm.device.unenroll", approvals_required: 1, description: "Unenrolling a device from management requires approval.", control: "Change-management control" },
      { policy_id: "endpoint-device-approve-config-push", effect: "require_approval", priority: 24, action: "mdm.config.push", approvals_required: 1, description: "Pushing a configuration profile to devices requires approval.", control: "Change-management control" },
      { policy_id: "endpoint-device-approve-app-remove", effect: "require_approval", priority: 28, action: "mdm.app.remove", approvals_required: 1, description: "Force-removing an app from managed devices requires approval.", control: "Change-management control" },
      { policy_id: "endpoint-device-deny-location-track", effect: "deny", priority: 10, action: "mdm.location.track", description: "Turning on device location tracking via an agent is never allowed.", control: "Privacy guard" },
      { policy_id: "endpoint-device-approve-restriction-modify", effect: "require_approval", priority: 26, action: "mdm.restriction.modify", approvals_required: 1, description: "Changing device restrictions or security baselines requires approval.", control: "Security-settings control" },
      { policy_id: "endpoint-device-approve-remote-control", effect: "require_approval", priority: 24, action: "mdm.remote.control", approvals_required: 1, description: "Starting a remote-control session on a device requires approval.", control: "Privileged-access control" },
      { policy_id: "endpoint-device-allow-inventory", effect: "allow", priority: 33, action: "mdm.inventory.read", description: "Reading device inventory is allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "networking-dns",
    name: "Networking, DNS & CDN (Cloudflare)",
    framework: "Availability & edge safety",
    blurb: "Guards the edge: no disabled WAF or DDoS protection, or SSL downgrades, and approvals on DNS, firewall, and routing changes that can cause an outage.",
    templates: [
      { policy_id: "networking-dns-approve-dns-modify", effect: "require_approval", priority: 22, action: "net.dns.modify", approvals_required: 1, description: "Changing a DNS record requires approval, a bad record can cause a full outage.", control: "Outage-prevention control" },
      { policy_id: "networking-dns-approve-firewall-modify", effect: "require_approval", priority: 22, action: "net.firewall.rule.modify", approvals_required: 1, description: "Changing a firewall rule requires approval.", control: "Network-security control" },
      { policy_id: "networking-dns-deny-waf-disable", effect: "deny", priority: 9, action: "net.waf.disable", description: "Disabling the web application firewall via an agent is never allowed.", control: "Security-control guard" },
      { policy_id: "networking-dns-deny-ddos-disable", effect: "deny", priority: 9, action: "net.ddos_protection.disable", description: "Disabling DDoS protection via an agent is never allowed.", control: "Availability guard" },
      { policy_id: "networking-dns-deny-ssl-downgrade", effect: "deny", priority: 9, action: "net.ssl.downgrade", description: "Downgrading or disabling TLS/SSL enforcement via an agent is never allowed.", control: "Transport-security guard" },
      { policy_id: "networking-dns-approve-cert-modify", effect: "require_approval", priority: 24, action: "net.cert.modify", approvals_required: 1, description: "Changing or replacing a TLS certificate requires approval.", control: "Transport-security control" },
      { policy_id: "networking-dns-approve-route-modify", effect: "require_approval", priority: 24, action: "net.route.modify", approvals_required: 1, description: "Changing edge routing or a load-balancer origin requires approval.", control: "Availability control" },
      { policy_id: "networking-dns-deny-ratelimit-disable", effect: "deny", priority: 11, action: "net.ratelimit.disable", description: "Disabling rate limiting via an agent is never allowed.", control: "Abuse-prevention guard" },
      { policy_id: "networking-dns-approve-cache-purge", effect: "require_approval", priority: 30, action: "net.cache.purge_all", approvals_required: 1, description: "Purging the entire CDN cache requires approval, it can spike origin load.", control: "Availability control" },
      { policy_id: "networking-dns-allow-read", effect: "allow", priority: 33, action: "net.*.read", description: "Reading DNS, firewall, and routing config is allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "secrets-kms",
    name: "Secrets & key management (Vault / KMS)",
    framework: "Cryptographic-material safety",
    blurb: "The tightest guardrails in the set: agents never read, export, or delete secrets and keys, and rotation cannot be turned off.",
    templates: [
      { policy_id: "secrets-kms-deny-secret-read", effect: "deny", priority: 8, action: "kms.secret.read", description: "Reading a stored secret via an agent is never allowed.", control: "Secrets guard" },
      { policy_id: "secrets-kms-deny-secret-export", effect: "deny", priority: 8, action: "kms.secret.export", description: "Exporting secrets via an agent is never allowed.", control: "Secrets guard" },
      { policy_id: "secrets-kms-deny-key-delete", effect: "deny", priority: 8, action: "kms.key.delete", description: "Deleting a cryptographic key via an agent is never allowed, it can render data unrecoverable.", control: "Cryptographic-material guard" },
      { policy_id: "secrets-kms-deny-rotation-disable", effect: "deny", priority: 9, action: "kms.rotation.disable", description: "Disabling automatic key rotation via an agent is never allowed.", control: "Key-hygiene guard" },
      { policy_id: "secrets-kms-deny-key-disable", effect: "deny", priority: 9, action: "kms.key.disable", description: "Disabling an active key via an agent is never allowed.", control: "Availability guard" },
      { policy_id: "secrets-kms-approve-key-rotate", effect: "require_approval", priority: 22, action: "kms.key.rotate", approvals_required: 1, description: "Rotating a key requires approval, callers may still hold the old one.", control: "Key-management control" },
      { policy_id: "secrets-kms-approve-grant", effect: "require_approval", priority: 22, action: "kms.grant", approvals_required: 1, description: "Granting access to a key or secret requires approval.", control: "Access-control change" },
      { policy_id: "secrets-kms-approve-policy-modify", effect: "require_approval", priority: 22, action: "kms.policy.modify", approvals_required: 1, description: "Changing a key or secret access policy requires approval.", control: "Access-control change" },
      { policy_id: "secrets-kms-deny-secret-share", effect: "deny", priority: 8, action: "kms.secret.share", description: "Sharing a secret with an external party via an agent is never allowed.", control: "Secrets guard" },
      { policy_id: "secrets-kms-deny-hsm-access", effect: "deny", priority: 8, action: "kms.hsm.access", description: "Direct HSM access via an agent is never allowed.", control: "Cryptographic-material guard" },
    ],
  },
  {
    key: "backup-dr",
    name: "Backup & disaster recovery",
    framework: "Data-recovery safety",
    blurb: "Guarantees you can recover: agents can never delete backups, disable schedules, or turn off encryption, and restores and retention changes need a human.",
    templates: [
      { policy_id: "backup-dr-deny-backup-delete", effect: "deny", priority: 8, action: "backup.delete", description: "Deleting a backup via an agent is never allowed.", control: "Data-recovery guard" },
      { policy_id: "backup-dr-deny-schedule-disable", effect: "deny", priority: 9, action: "backup.schedule.disable", description: "Disabling a backup schedule via an agent is never allowed.", control: "Data-recovery guard" },
      { policy_id: "backup-dr-deny-encryption-disable", effect: "deny", priority: 9, action: "backup.encryption.disable", description: "Disabling backup encryption via an agent is never allowed.", control: "Data-protection guard" },
      { policy_id: "backup-dr-approve-restore", effect: "require_approval", priority: 24, action: "backup.restore", approvals_required: 1, description: "Restoring from a backup requires approval, it can overwrite live data.", control: "Data-recovery control" },
      { policy_id: "backup-dr-approve-retention-modify", effect: "require_approval", priority: 22, action: "backup.retention.modify", approvals_required: 1, description: "Shortening backup retention requires approval.", control: "Records-retention control" },
      { policy_id: "backup-dr-deny-vault-delete", effect: "deny", priority: 8, action: "backup.vault.delete", description: "Deleting a backup vault or its immutability lock via an agent is never allowed.", control: "Data-recovery guard" },
      { policy_id: "backup-dr-deny-offsite-disable", effect: "deny", priority: 10, action: "backup.offsite.disable", description: "Disabling offsite or cross-region backup replication via an agent is never allowed.", control: "Resilience guard" },
      { policy_id: "backup-dr-approve-replicate-modify", effect: "require_approval", priority: 24, action: "backup.replicate.modify", approvals_required: 1, description: "Changing backup replication settings requires approval.", control: "Resilience control" },
      { policy_id: "backup-dr-allow-status", effect: "allow", priority: 33, action: "backup.status.read", description: "Reading backup status and history is allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "privacy-dsar",
    name: "Privacy & data-subject requests",
    framework: "Privacy operations",
    blurb: "Puts a human on the sensitive steps of privacy operations: erasure, export, consent changes, and cross-border transfer, and never skips identity verification.",
    templates: [
      { policy_id: "privacy-dsar-approve-erase", effect: "require_approval", priority: 22, action: "dsar.erase", approvals_required: 1, description: "Erasing a data subject's records requires approval, erasure is irreversible.", control: "Right-to-erasure control" },
      { policy_id: "privacy-dsar-approve-export", effect: "require_approval", priority: 24, action: "dsar.export", approvals_required: 1, description: "Exporting a data subject's personal data requires approval.", control: "Data-portability control" },
      { policy_id: "privacy-dsar-deny-verify-skip", effect: "deny", priority: 9, action: "dsar.identity.verify.skip", description: "Skipping identity verification on a privacy request via an agent is never allowed.", control: "Identity-verification guard" },
      { policy_id: "privacy-dsar-approve-consent-modify", effect: "require_approval", priority: 26, action: "dsar.consent.modify", approvals_required: 1, description: "Changing a data subject's consent record requires approval.", control: "Consent-integrity control" },
      { policy_id: "privacy-dsar-deny-optout-override", effect: "deny", priority: 9, action: "dsar.optout.override", description: "Overriding a do-not-sell or opt-out choice via an agent is never allowed.", control: "Consent-integrity guard" },
      { policy_id: "privacy-dsar-approve-transfer", effect: "require_approval", priority: 24, action: "dsar.data.transfer", approvals_required: 1, conditions: [{ field: "cross_border", op: "eq", value: true }], description: "Cross-border transfer of personal data requires approval.", control: "Transfer-control" },
      { policy_id: "privacy-dsar-approve-retention-override", effect: "require_approval", priority: 26, action: "dsar.retention.override", approvals_required: 1, description: "Overriding a retention rule on a privacy request requires approval.", control: "Records-retention control" },
      { policy_id: "privacy-dsar-approve-third-party-forward", effect: "require_approval", priority: 24, action: "dsar.third_party.forward", approvals_required: 1, description: "Forwarding an erasure or opt-out to a downstream processor requires approval.", control: "Processor-control" },
      { policy_id: "privacy-dsar-approve-deadline-extend", effect: "require_approval", priority: 30, action: "dsar.deadline.extend", approvals_required: 1, description: "Extending a statutory response deadline requires approval.", control: "Compliance-control" },
      { policy_id: "privacy-dsar-allow-status", effect: "allow", priority: 33, action: "dsar.request.read", description: "Reading the status of a privacy request is allowed.", control: "Least-friction reads" },
    ],
  },
  {
    key: "ccpa",
    name: "CCPA / CPRA",
    framework: "California consumer privacy",
    blurb: "The California-specific consumer-rights controls: honor opt-outs, gate sale or sharing of personal information, and put erasure behind a human.",
    templates: [
      { policy_id: "ccpa-deny-sell-optout-override", effect: "deny", priority: 9, action: "data.share", resource: "optout:*", description: "Selling or sharing the personal information of a consumer who opted out is never allowed.", control: "CCPA 1798.120 (Right to opt out)" },
      { policy_id: "ccpa-approve-pi-sale", effect: "require_approval", priority: 24, action: "data.sell", resource: "pii:*", approvals_required: 1, description: "Selling or sharing personal information requires approval.", control: "CCPA 1798.115 (Sale disclosure)" },
      { policy_id: "ccpa-approve-erasure", effect: "require_approval", priority: 24, action: "consumer.delete", approvals_required: 1, description: "Deleting a consumer's personal information requires approval.", control: "CCPA 1798.105 (Right to delete)" },
      { policy_id: "ccpa-approve-pi-export", effect: "require_approval", priority: 26, action: "*.export", resource: "pii:*", approvals_required: 1, description: "Exporting personal information for a consumer request requires approval.", control: "CCPA 1798.110 (Right to know)" },
    ],
  },
  {
    key: "ferpa",
    name: "FERPA",
    framework: "Student education records",
    blurb: "Controls for anyone handling student data: no disclosing or deleting education records, and approvals on access and export.",
    templates: [
      { policy_id: "ferpa-deny-record-disclose", effect: "deny", priority: 9, action: "*.share", resource: "student:*", description: "Disclosing a student education record to any party via an agent is never allowed.", control: "FERPA 34 CFR 99.30 (Consent to disclose)" },
      { policy_id: "ferpa-approve-record-read", effect: "require_approval", priority: 26, action: "*.read", resource: "student:*", approvals_required: 1, description: "Accessing a student education record requires approval.", control: "FERPA 34 CFR 99.31 (Access control)" },
      { policy_id: "ferpa-approve-record-export", effect: "require_approval", priority: 24, action: "*.export", resource: "student:*", approvals_required: 1, description: "Exporting student records requires approval.", control: "FERPA 34 CFR 99.31 (Disclosure)" },
      { policy_id: "ferpa-deny-record-delete", effect: "deny", priority: 11, action: "*.delete", resource: "student:*", description: "Deleting a student education record via an agent is never allowed.", control: "FERPA 34 CFR 99.10 (Recordkeeping)" },
    ],
  },
  {
    key: "glba",
    name: "GLBA",
    framework: "Consumer financial data",
    blurb: "Safeguards-Rule controls for nonpublic personal financial information: no disclosure to third parties, and approvals on access and export.",
    templates: [
      { policy_id: "glba-deny-npi-disclose", effect: "deny", priority: 9, action: "data.share", resource: "npi:*", description: "Disclosing nonpublic personal financial information to a third party via an agent is never allowed.", control: "GLBA Privacy Rule (Disclosure limits)" },
      { policy_id: "glba-approve-npi-read", effect: "require_approval", priority: 26, action: "*.read", resource: "npi:*", approvals_required: 1, description: "Accessing consumer financial information requires approval.", control: "GLBA Safeguards Rule (Access control)" },
      { policy_id: "glba-approve-npi-export", effect: "require_approval", priority: 24, action: "*.export", resource: "npi:*", approvals_required: 1, description: "Exporting consumer financial information requires approval.", control: "GLBA Safeguards Rule (Data protection)" },
      { policy_id: "glba-deny-encryption-disable", effect: "deny", priority: 9, action: "*.encryption.disable", resource: "npi:*", description: "Disabling encryption on consumer financial data via an agent is never allowed.", control: "GLBA Safeguards Rule 314.4(c) (Encryption)" },
    ],
  },
  {
    key: "eu-ai-act",
    name: "EU AI Act",
    framework: "AI system obligations",
    blurb: "Obligations for deploying AI in the EU: no prohibited uses, human oversight on high-risk decisions, and transparency and logging that cannot be turned off.",
    templates: [
      { policy_id: "eu-ai-act-deny-prohibited-use", effect: "deny", priority: 8, action: "ai.deploy", resource: "use:prohibited*", description: "Deploying an AI system for a prohibited use (social scoring, untargeted scraping, manipulation) is never allowed.", control: "EU AI Act Art. 5 (Prohibited practices)" },
      { policy_id: "eu-ai-act-approve-high-risk-decision", effect: "require_approval", priority: 22, action: "ai.decision.finalize", approvals_required: 1, conditions: [{ field: "risk", op: "eq", value: "high" }], description: "Finalizing a high-risk automated decision requires human oversight.", control: "EU AI Act Art. 14 (Human oversight)" },
      { policy_id: "eu-ai-act-deny-log-disable", effect: "deny", priority: 8, action: "ai.logging.disable", description: "Disabling AI system logging is never allowed.", control: "EU AI Act Art. 12 (Record-keeping)" },
      { policy_id: "eu-ai-act-approve-model-deploy", effect: "require_approval", priority: 24, action: "ai.model.deploy", approvals_required: 1, description: "Deploying or materially changing an AI model requires approval.", control: "EU AI Act Art. 9 (Risk management)" },
      { policy_id: "eu-ai-act-deny-transparency-remove", effect: "deny", priority: 10, action: "ai.disclosure.remove", description: "Removing the AI-interaction disclosure shown to users is never allowed.", control: "EU AI Act Art. 50 (Transparency)" },
    ],
  },
  {
    key: "iso42001",
    name: "ISO 42001",
    framework: "AI management system",
    blurb: "AIMS controls for governing AI responsibly: change control on models and data, an impact assessment before deployment, and protected audit records.",
    templates: [
      { policy_id: "iso42001-approve-model-change", effect: "require_approval", priority: 24, action: "ai.model.deploy", approvals_required: 1, description: "Deploying or updating a model requires approval and a documented change.", control: "ISO 42001 A.6.2 (AI system life cycle)" },
      { policy_id: "iso42001-approve-training-data", effect: "require_approval", priority: 24, action: "ai.training_data.modify", approvals_required: 1, description: "Changing training data requires approval.", control: "ISO 42001 A.7.4 (Data for AI systems)" },
      { policy_id: "iso42001-deny-impact-skip", effect: "deny", priority: 10, action: "ai.deploy", conditions: [{ field: "impact_assessment", op: "eq", value: false }], description: "Deploying an AI system without a completed impact assessment is never allowed.", control: "ISO 42001 A.5.2 (AI impact assessment)" },
      { policy_id: "iso42001-deny-audit-record-delete", effect: "deny", priority: 8, action: "ai.audit_record.delete", description: "Deleting AI governance audit records via an agent is never allowed.", control: "ISO 42001 A.9.2 (Documented information)" },
      { policy_id: "iso42001-approve-autonomy-increase", effect: "require_approval", priority: 22, action: "ai.autonomy.increase", approvals_required: 1, description: "Increasing an AI system's autonomy or scope requires approval.", control: "ISO 42001 A.6.2.6 (Operation and monitoring)" },
    ],
  },
  {
    key: "cms-publishing",
    name: "CMS & web publishing",
    framework: "Website safety",
    blurb: "Protects the public website: approvals on publishing, domain changes, and user roles, and a lock on injected scripts and deleted pages.",
    templates: [
      { policy_id: "cms-publishing-approve-publish", effect: "require_approval", priority: 24, action: "cms.publish", approvals_required: 1, description: "Publishing content to the live site requires approval.", control: "Change-management control" },
      { policy_id: "cms-publishing-deny-page-delete", effect: "deny", priority: 12, action: "cms.page.delete", description: "Deleting a live page via an agent is never allowed.", control: "Destructive-action guard" },
      { policy_id: "cms-publishing-deny-script-inject", effect: "deny", priority: 8, action: "cms.script.inject", description: "Injecting a custom script or tracking tag via an agent is never allowed, it can exfiltrate visitor data.", control: "Supply-chain guard" },
      { policy_id: "cms-publishing-approve-domain-modify", effect: "require_approval", priority: 22, action: "cms.domain.modify", approvals_required: 1, description: "Changing the site's domain or DNS mapping requires approval.", control: "Outage-prevention control" },
      { policy_id: "cms-publishing-approve-user-role", effect: "require_approval", priority: 24, action: "cms.user.role.modify", approvals_required: 1, description: "Changing a CMS user's role requires approval.", control: "Access-control change" },
      { policy_id: "cms-publishing-approve-plugin-install", effect: "require_approval", priority: 24, action: "cms.plugin.install", approvals_required: 1, description: "Installing a plugin or theme requires approval.", control: "Supply-chain control" },
      { policy_id: "cms-publishing-approve-redirect-modify", effect: "require_approval", priority: 26, action: "cms.redirect.modify", approvals_required: 1, description: "Changing URL redirects requires approval, they affect SEO and access.", control: "Change-management control" },
      { policy_id: "cms-publishing-approve-form-export", effect: "require_approval", priority: 24, action: "cms.form.export", approvals_required: 1, description: "Exporting form submissions requires approval, they often contain PII.", control: "Data-egress control" },
      { policy_id: "cms-publishing-deny-robots-modify", effect: "deny", priority: 13, action: "cms.robots.modify", description: "Changing robots.txt or noindex directives via an agent is never allowed, it can deindex the whole site.", control: "SEO-integrity guard" },
      { policy_id: "cms-publishing-allow-preview", effect: "allow", priority: 33, action: "cms.preview.read", description: "Reading drafts and previews is allowed.", control: "Least-friction reads" },
    ],
  },
];

// Display grouping for the policy library. Every pack key belongs to exactly one
// category; a key not listed here falls into "More" in the UI. Order here is the
// order sections render in.
export const PACK_CATEGORIES: { name: string; keys: string[] }[] = [
  { name: "Foundational", keys: ["ai-usage", "baseline", "governance", "trust-tiers", "velocity"] },
  { name: "Compliance frameworks", keys: ["soc2", "hipaa", "pci", "gdpr", "iso27001", "nist-ai", "ccpa", "ferpa", "glba", "eu-ai-act", "iso42001"] },
  { name: "Money & finance", keys: ["payments-plus", "finance-accounting", "ecommerce", "marketing-ads"] },
  { name: "Data & databases", keys: ["data-integrity", "database-admin", "data-warehouse", "backup-dr", "privacy-dsar"] },
  { name: "Infrastructure & cloud", keys: ["infra", "cloud-iam", "source-control", "cicd", "kubernetes", "networking-dns"] },
  { name: "Identity, access & secrets", keys: ["access-security", "directory-identity", "endpoint-device", "secrets-kms"] },
  { name: "Business apps", keys: ["email-comms", "crm-sales", "support-helpdesk", "collaboration", "hr-people", "legal-contracts", "cms-publishing"] },
];

export function packByKey(key: string): PolicyPack | undefined {
  return POLICY_PACKS.find((p) => p.key === key);
}

// Total number of ready-made policies across the whole library (used for the
// "N policies available" figure on marketing and the library header).
export function totalTemplateCount(): number {
  return POLICY_PACKS.reduce((n, p) => n + p.templates.length, 0);
}
